version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/de-supported-rhel9:latest'

dependencies:
  galaxy:
    collections:
      - ansible.eda
      - servicenow.itsm
  system: 
    - iputils [platform:rpm]
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
    - gcc [platform:rpm]
    - python3.11-devel [platform:rpm]
  python_interpreter:
    package_system: "python3.11"

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_base:
    - ENV SN_HOST="https://<instance-name>.service-now.com"
    - ENV SN_USERNAME="<the username>"
    - ENV SN_PASSWORD="<the password>"
